# Trix.config.lang =
#   bold: "Bold"
#   bullets: "Bullets"
#   byte:  "Byte"
#   bytes: "Bytes"
#   captionPlaceholder: "Add a caption…"
#   code: "Code"
#   heading1: "Heading"
#   indent: "Increase Level"
#   italic: "Italic"
#   link: "Link"
#   numbers: "Numbers"
#   outdent: "Decrease Level"
#   quote: "Quote"
#   redo: "Redo"
#   remove: "Remove"
#   strike: "Strikethrough"
#   undo: "Undo"
#   unlink: "Unlink"
#   url: "URL"
#   urlPlaceholder: "Enter a URL…"
#   GB: "GB"
#   KB: "KB"
#   MB: "MB"
#   PB: "PB"
#   TB: "TB"
# 
Trix.config.lang =
  bold: "粗体"
  bullets: "无序列表"
  byte:  "字节"
  bytes: "字节"
  captionPlaceholder: "添加图片注释（可选）"
  code: "代码块"
  heading1: "标题"
  # indent: "增加缩进"
  italic: "斜体"
  link: "插入链接"
  numbers: "有序列表"
  # outdent: "减少缩进"
  quote: "引用块"
  redo: "前进"
  remove: "删除"
  # strike: "删除线"
  undo: "后退"
  unlink: "删除链接"
  url: "URL"
  urlPlaceholder: "输入 URL"
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"